spring.application.name=barberia-api

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/barberia_db
spring.datasource.username=barberia_user
spring.datasource.password=barberia_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (clave temporal de desarrollo; en Fase 7 la moveremos a variable de entorno)
app.jwt.secret=cambia_esta_clave_por_una_de_al_menos_256_bits_para_hs256_dev
app.jwt.expiration-ms=86400000

# Puerto del servidor
server.port=8080
